class TreatmentPlanGenerator:

    def generate_plan(
        self,
        mutations,
        therapies,
        cancer_type,
        patient_id,
        age,
        sex,
        stage
    ):

        mutation_list = ", ".join(mutations)

        therapy_text = ""

        for drug in therapies:
            therapy_text += f"- {drug}\n"


        plan = f"""
PharmaTab AI Oncology Report
====================================================

Patient Clinical Summary
----------------------------------------------------

Patient ID: {patient_id}
Cancer Type: {cancer_type}
Age: {age}
Sex: {sex}
Stage: {stage}


Genomic Alterations
----------------------------------------------------

Detected driver mutations:

{mutation_list}

These mutations are associated with dysregulated signaling
pathways contributing to tumor growth.


Recommended Targeted Therapies
----------------------------------------------------

{therapy_text}


Treatment Strategy
----------------------------------------------------

1. Initiate targeted therapy based on detected mutations
2. Monitor tumor response using imaging
3. Adjust therapy if resistance mutations emerge
4. Consider combination therapy if disease progresses


Monitoring Plan
----------------------------------------------------

- Radiologic imaging every 6–8 weeks
- Tumor marker tracking
- Genomic mutation monitoring


AI Risk Assessment
----------------------------------------------------

Moderate probability of therapy resistance over time.


Report Generated By
----------------------------------------------------

PharmaTab AI Oncology Platform
Genomic Analysis + Tumor Evolution Modeling
"""

        return plan